# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='task',
            new_name='content',
        ),
    ]
